spring:
  profiles:
    active : local
  application:
    name: "oauth-demo-backend"

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    root: debug
    me.cocoblue: debug